### ISSUE TITLE
Dictionary download

### ISSUE THREAD

**Issue by guoyinwang** [tca19/dict2vec#2]
Hi,

First, I want to thank the good Readme effort for this repo and provide the dictionary download code. It helps a lot.

I am trying to download wordlist through the dowload-definition, but it seems that dictionary.com have changed their web code. So the crawling function for this website no longer works. I am not an expert in web crawling, so want to check if it is easy for the author to update this part of code.

Thanks,
Guoyin

**Comment by tca19** [comment]
Hi Guoyin,

Thank you for your interest in dict2vec software. Indeed the html source of dictionary.com have changed. I fixed the problem in the downloader script and it works now. I also noticed that the downloader for Collins was not working anymore and fixed the issue as well.

You can run the `./downloader.py` script in the `dict-dl` folder to see that everything works now, and that I added a functionality to specify if we want to only download the *verb* , *adjective* or *noun* definitions of a word (see the `__main__` in `downloader.py`).

I will update the `download_definition.py` program and the README to mention that this new feature exists.

**Comment by StalVars** [comment]
Does this work now? I used the 'download_defnitions.py',

1) the urllib.request.urlopen gives "http.client.RemoteDisconnected: Remote end closed connection without response", 
2) I replaced with requests.get(.) using mozilla, it retrieves the html but seems to have a different html format that the script, 'downloader.py' cannot identify the defnitions now
