### ISSUE TITLE
Download links are dead

### ISSUE THREAD

**Issue by forgetso** [tca19/dict2vec#4]
Hi, the links to your AWS bucket are dead. Do you have updated ones?

Thanks

**Comment by tca19** [comment]
Hello @forgetso 

Indeed, my AWS student account has been terminated lately and I had not noticed (links were still working in July). Thank you for pointing this out. I have a backup of the files needed to train the vectors (files containing strong and weak pairs) so I will upload them to a new AWS account. Concerning the pre-trained vectors, unfortunately, I only have a backup of the 300-dimensional vectors trained on the entire Wikipedia. I don't have a backup of the vectors trained on the 50M and the 200M tokens corpora. I will retrain them and upload them as well on AWS.
I will let this issue open and update it with new comments when it is done.

**Comment by tca19** [comment]
I have uploaded some files (`enwiki-50M`, `strong-pairs.txt` and `weak-pairs.txt`) on a S3 bucket with a different AWS account. I used the same bucket name, so the links in `demo-train.sh` do not have to be changed to work again. Now, those links are valid and the script `demo-train.sh` works fine to train word vectors on a small Wikipedia corpus.

I still have to train again word vectors on the 200M tokens Wikipedia corpus and upload all word vectors.

**Comment by forgetso** [comment]
Thanks for the update, I really appreciate you taking the time to fix the links. I am hoping to use your dict2vec vectors in a project and potentially train my own with different dictionary data scraped from online dictionaries.

**Comment by tca19** [comment]
Hello @forgetso 

I finally finished re-training the word embeddings. I have uploaded them to a Mega account and I have replaced the links to download them in the README. You should now by able to download the pre-trained dict2vec vectors by clicking the links in the README. I am closing this issue now, but feel free to open a new one if you have any trouble using them in your project, I will be glad to help if needed.

**Comment by forgetso** [comment]
Thanks for this. The word embeddings are already proving interesting compared to the other embeddings I'm using. For example, if I take two words and take the similarity in the dict2vec model, a wikipedia model, and a common crawl model, I see considerable differences between dict2vec and the other models in about 50% of my sample pairs. This difference highlights where words are related but are not the same (synonyms), which is very useful to me.

e.g. examples where `abs( dict2vec_similarity - other_similarity ) > 0.2`

scientist --> professional (instance-of)
pregnancy --> birth (part-of / meronym)
mountains --> tall (attribute)

**Comment by forgetso** [comment]
I have sent you a tip via [Brave](https://brave.com/) for your help.

**Comment by tca19** [comment]
@forgetso 

Great! It is always nice for me to see other people using my work successfully in their research.
Thank you for the tip!
